### ISSUE TITLE
ImportError: No module named plugnplay

### ISSUE THREAD

**Issue by welshboy** [Eldorados/script.module.urlresolver#358]
Trying to use SALTS and Velocity plugins with Kodi, both of which rely on the URLResolver. I am Getting this error when trying to load a stream.

    18:32:13 T:1741021808 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
    NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
    Error Type: <type 'exceptions.ImportError'>
    Error Contents: No module named plugnplay
    Traceback (most recent call last):
    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.salts/default.py", line 2347, in <module>
    sys.exit(main())
    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.salts/default.py", line 2338, in main
    url_dispatcher.dispatch(mode, queries)
    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.salts/salts_lib/url_dispatcher.py", line 80, in dispatch
    self.func_registry[mode](*args, **kwargs)
    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.salts/default.py", line 1072, in get_sources
    hosters = apply_urlresolver(hosters)
    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.salts/default.py", line 1103, in apply_urlresolver
    import urlresolver.plugnplay
    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urlresolver/lib/urlresolver/__init__.py", line 33, in <module>
    import plugnplay
    ImportError: No module named plugnplay
    -->End of Python script error report<--

Here's the link to the full log. http://xbmclogs.com/pafnvpqhi

This error occurs when I select a program/movie within SALTs. It then searches for links successfully. It doesn't display any of the links, or the popup dialogue however. Just an error saying to look at the log.

**Comment by Eldorados** [comment]
Your urlresolver installation seems to be gone bad, best thing to do is try uninstalling and let it re-install and hopefully all files will be included this time

**Comment by welshboy** [comment]
Yeah I thought as much. When I click uninstalling it says can't be uninstalled because it's being used by salts, phoenix etc... any way to solve this? Maybe manually remove it?
